//! Artwork cache tests.
//!
//! Every image here is generated by [`fixtures::synthetic_png`] - a few solid
//! pixels encoded on the spot. No real cover art appears in this repository, and a
//! generated image is also the only way to assert an exact size or a deliberately
//! malformed byte stream.
//!
//! No test contacts a RomM instance. The transport is a fake that answers from a
//! script, so "what happens when the response is 9 MB" is a decision the test
//! makes rather than something it hopes for.

use super::fixtures::synthetic_png;
use super::*;
use crate::identity_source::net_policy::StaticResolver;
use crate::identity_source::path_map::ProviderPathKind;
use crate::identity_source::romm::client::RommHttpResponse;
use crate::identity_source::romm::config::{RommSourceConfig, RommToken};
use std::sync::Mutex;

const SERVER: &str = "http://172.19.0.20:8080";
const FIXTURE_TOKEN: &str = "artwork-test-token-never-printed";

// --- Fixtures -------------------------------------------------------------

struct Tree {
    root: PathBuf,
}

impl Tree {
    fn new(label: &str) -> Self {
        let root = std::env::temp_dir().join(format!(
            "archivefs-artwork-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|value| value.as_nanos())
                .unwrap_or(0)
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("identity")).expect("fixture");
        Self { root }
    }

    fn identity(&self) -> PathBuf {
        self.root.join("identity")
    }

    fn cache(&self) -> ArtworkCache {
        ArtworkCache::new(&self.identity(), IdentityProvider::Romm)
    }
}

impl Drop for Tree {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

fn source() -> ValidatedRommSource {
    let config = RommSourceConfig {
        enabled: true,
        url: SERVER.to_string(),
        mappings: Vec::new(),
        provider_path_kind: ProviderPathKind::ProviderRelative,
        token_path: None,
    };
    let token = RommToken::parse(FIXTURE_TOKEN).expect("token");
    ValidatedRommSource::validate(&config, &token, &[], &StaticResolver::new())
        .expect("the fixture source should validate")
}

/// A transport that answers artwork requests from a script and records what was
/// asked for, including whether a credential was offered.
struct FakeArtworkServer {
    responses: Mutex<Vec<Result<RommHttpResponse, RommRequestError>>>,
    requests: Mutex<Vec<(String, bool)>>,
}

impl FakeArtworkServer {
    fn serving(bytes: Vec<u8>) -> Self {
        Self::scripted(vec![Ok(RommHttpResponse {
            status: 200,
            body: bytes,
            location: None,
        })])
    }

    fn scripted(responses: Vec<Result<RommHttpResponse, RommRequestError>>) -> Self {
        Self {
            responses: Mutex::new(responses),
            requests: Mutex::new(Vec::new()),
        }
    }

    fn requests(&self) -> Vec<(String, bool)> {
        self.requests.lock().expect("lock").clone()
    }

    fn request_count(&self) -> usize {
        self.requests.lock().expect("lock").len()
    }
}

impl RommTransport for FakeArtworkServer {
    fn get(
        &self,
        url: &str,
        authorization: Option<&str>,
        _max_bytes: usize,
        _timeout: std::time::Duration,
    ) -> Result<RommHttpResponse, RommRequestError> {
        self.requests
            .lock()
            .expect("lock")
            .push((url.to_string(), authorization.is_some()));
        let mut responses = self.responses.lock().expect("lock");
        if responses.is_empty() {
            return Err(RommRequestError::Transport {
                detail: "the script ran out of responses".to_string(),
            });
        }
        responses.remove(0)
    }
}

fn request<'a>(id: &'a str, small: Option<&'a str>, public: Option<&'a str>) -> ArtworkRequest<'a> {
    ArtworkRequest {
        provider_game_id: id,
        kind: ArtworkKind::Cover,
        small_reference: small,
        public_reference: public,
    }
}

/// The shape RomM really produces, timestamp query and all.
const REAL_SMALL_REFERENCE: &str =
    "/assets/romm/resources/roms/149/1/cover/small.png?ts=2026-07-30 21:52:52";

// --- Fetch policy: where artwork may come from ----------------------------

#[test]
fn a_romm_hosted_cover_is_fetched_and_thumbnailed() {
    let tree = Tree::new("fetch-ok");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(162, 216));

    let thumbnail = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some(REAL_SMALL_REFERENCE), None),
            1_000,
            None,
        )
        .expect("a RomM-hosted PNG cover should be cached");

    assert_eq!(
        thumbnail.width, 162,
        "already inside the box, so not resized"
    );
    assert_eq!(thumbnail.height, 216);
    assert!(thumbnail.path.is_file());
    assert!(thumbnail.bytes > 0);

    // The space in RomM's own `ts` query has to be encoded, or the request line is
    // not a valid one.
    let (url, offered_token) = server.requests().remove(0);
    assert!(url.starts_with(SERVER), "{url}");
    assert!(!url.contains(' '), "the URL must be encoded: {url}");
    assert!(url.contains("%20"), "{url}");
    assert!(
        !offered_token,
        "artwork needs no credential, so none should be offered first"
    );
}

#[test]
fn a_public_scraper_url_is_never_fetched() {
    let tree = Tree::new("public-refused");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(10, 10));

    // The real shape: RomM has an igdb.com cover and no local one.
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request(
                "1",
                None,
                Some("https://images.igdb.com/igdb/image/upload/t_1080p/co2w66.jpg"),
            ),
            1_000,
            None,
        )
        .expect_err("a public host must not be fetched");
    assert_eq!(refusal.code(), "remote_host_not_allowed");
    assert!(
        refusal.detail().contains("images.igdb.com"),
        "{}",
        refusal.detail()
    );
    assert!(
        refusal.is_permanent(),
        "there is no point asking again, so this must not become a request storm"
    );
    assert_eq!(
        server.request_count(),
        0,
        "not one request should have left the process"
    );
}

#[test]
fn a_public_screenshot_reference_is_refused_without_a_request() {
    let tree = Tree::new("public-screenshot-refused");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(10, 10));
    let media = crate::identity_source::model::MediaReference {
        hosted_reference: None,
        public_reference: Some("https://images.example/screenshot.jpg".to_string()),
    };
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &ArtworkRequest::from_media("1", &media),
            1_000,
            None,
        )
        .expect_err("a public screenshot host must not be fetched");
    assert_eq!(refusal.code(), "remote_host_not_allowed");
    assert_eq!(server.request_count(), 0);
}

/// Relative-URL forms that change the host are refusals, not requests.
#[test]
fn a_reference_that_escapes_the_approved_origin_is_refused() {
    let tree = Tree::new("escape-refused");
    let cache = tree.cache();
    for hostile in [
        "//evil.example/cover.png",
        "http://evil.example/cover.png",
        "https://172.19.0.20:8080/cover.png",
        "http://172.19.0.20:9999/cover.png",
    ] {
        let server = FakeArtworkServer::serving(synthetic_png(10, 10));
        let refusal = cache
            .fetch(
                &source(),
                &server,
                &request("1", Some(hostile), None),
                1_000,
                None,
            )
            .unwrap_err();
        assert!(
            matches!(
                refusal.code(),
                "remote_host_not_allowed" | "unsupported_reference"
            ),
            "{hostile} produced {}",
            refusal.code()
        );
        assert_eq!(
            server.request_count(),
            0,
            "{hostile} must not produce a request"
        );
    }

    // A `..` in the path is a different matter: the URL parser resolves it before
    // anything is sent, and the result is still the approved origin - so it is a
    // harmless request for a path RomM will not have, not an escape. Asserting the
    // safe outcome rather than a refusal is the honest test.
    let server = FakeArtworkServer::serving(synthetic_png(10, 10));
    cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/a/../../etc/passwd"), None),
            1_000,
            None,
        )
        .expect("a normalised path on the approved origin is not an escape");
    let (url, _) = server.requests().remove(0);
    assert_eq!(
        url,
        format!("{SERVER}/etc/passwd"),
        "the `..` should have been resolved away, and the host kept"
    );
}

#[test]
fn a_record_with_no_artwork_at_all_says_so_once() {
    let tree = Tree::new("no-artwork");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(10, 10));
    let refusal = cache
        .fetch(&source(), &server, &request("1", None, None), 1_000, None)
        .expect_err("nothing to fetch");
    assert_eq!(refusal.code(), "no_artwork");
    assert!(refusal.is_permanent());
    assert_eq!(server.request_count(), 0);
}

#[test]
fn the_token_is_offered_only_after_the_instance_refuses_without_it() {
    let tree = Tree::new("token-retry");
    let cache = tree.cache();
    let server = FakeArtworkServer::scripted(vec![
        Ok(RommHttpResponse {
            status: 401,
            body: Vec::new(),
            location: None,
        }),
        Ok(RommHttpResponse {
            status: 200,
            body: synthetic_png(80, 100),
            location: None,
        }),
    ]);
    let thumbnail = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("the retry with a credential should succeed");
    assert_eq!(thumbnail.width, 80);

    let requests = server.requests();
    assert_eq!(requests.len(), 2);
    assert!(!requests[0].1, "the first attempt offers no credential");
    assert!(requests[1].1, "the retry does");
}

// --- Validation: what the bytes have to be --------------------------------

#[test]
fn a_response_that_is_not_an_image_is_refused_by_its_bytes() {
    let tree = Tree::new("not-an-image");
    let cache = tree.cache();
    // An HTML error page served with a 200, which is exactly what a misconfigured
    // reverse proxy does.
    let server = FakeArtworkServer::serving(b"<!doctype html><html>404</html>".to_vec());
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("HTML is not a cover");
    assert_eq!(refusal.code(), "not_an_image");
    assert!(refusal.is_permanent());
}

#[test]
fn a_declared_content_type_cannot_override_the_magic_bytes() {
    // The declared type is a claim; the bytes are the fact. `detect_format` is
    // given nothing but bytes, which is what makes the claim irrelevant.
    assert_eq!(detect_format(&synthetic_png(4, 4)), Some(ImageFormat::Png));
    assert_eq!(
        detect_format(&[0xff, 0xd8, 0xff, 0x00]),
        Some(ImageFormat::Jpeg)
    );
    assert_eq!(detect_format(b"GIF89a...."), Some(ImageFormat::Gif));
    assert_eq!(
        detect_format(b"RIFF\0\0\0\0WEBPVP8 "),
        Some(ImageFormat::WebP)
    );
    assert_eq!(detect_format(b"not an image at all"), None);
    assert_eq!(detect_format(&[]), None);
}

#[test]
fn a_format_this_build_does_not_decode_is_named_in_the_refusal() {
    let tree = Tree::new("jpeg-named");
    let cache = tree.cache();
    // A JPEG signature with nothing behind it: enough to be identified.
    let server = FakeArtworkServer::serving(vec![0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10]);
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("this build reads PNG only");
    assert_eq!(refusal.code(), "not_an_image");
    assert!(
        refusal.detail().contains("JPEG"),
        "the refusal should say what it was: {}",
        refusal.detail()
    );
}

#[test]
fn a_corrupt_png_is_refused_rather_than_stored() {
    let tree = Tree::new("corrupt-png");
    let cache = tree.cache();
    // A valid signature followed by rubbish.
    let mut corrupt = synthetic_png(20, 20);
    corrupt.truncate(30);
    corrupt.extend_from_slice(&[0u8; 40]);
    let server = FakeArtworkServer::serving(corrupt);
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("a broken PNG cannot become a thumbnail");
    assert!(
        matches!(refusal.code(), "decode_failed" | "not_an_image"),
        "{}",
        refusal.code()
    );
    assert!(
        cache.keys(SERVER).is_empty(),
        "nothing should have been indexed"
    );
}

#[test]
fn an_oversized_response_is_refused_without_being_decoded() {
    let tree = Tree::new("oversized");
    let cache = tree.cache();
    let server = FakeArtworkServer::scripted(vec![Err(RommRequestError::ResponseTooLarge {
        limit: MAX_ARTWORK_RESPONSE_BYTES,
    })]);
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("over the ceiling");
    assert_eq!(refusal.code(), "response_too_large");
}

#[test]
fn an_image_with_excessive_dimensions_is_refused() {
    let tree = Tree::new("huge-dimensions");
    let cache = tree.cache();
    // Larger than the per-side ceiling, but still a small file - which is exactly
    // the shape of a decompression bomb.
    let server = FakeArtworkServer::serving(synthetic_png(MAX_SOURCE_DIMENSION + 1, 8));
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("too many pixels per side");
    assert_eq!(refusal.code(), "dimensions_too_large");
    assert!(refusal.is_permanent());
    assert!(cache.keys(SERVER).is_empty());
}

#[test]
fn a_transport_timeout_is_reported_and_is_not_permanent() {
    let tree = Tree::new("timeout");
    let cache = tree.cache();
    let server = FakeArtworkServer::scripted(vec![Err(RommRequestError::Timeout)]);
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect_err("timed out");
    assert_eq!(refusal.code(), "timeout");
    assert!(
        !refusal.is_permanent(),
        "a timeout is worth retrying, unlike a public-host refusal"
    );
}

#[test]
fn cancellation_stops_a_fetch_before_it_stores_anything() {
    let tree = Tree::new("cancel");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(60, 80));
    let cancel = AtomicBool::new(true);
    let refusal = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            Some(&cancel),
        )
        .expect_err("cancelled");
    assert_eq!(refusal.code(), "cancelled");
    assert!(cache.keys(SERVER).is_empty());
    assert_eq!(
        server.request_count(),
        0,
        "cancellation should be noticed before the request"
    );
}

// --- Thumbnailing ---------------------------------------------------------

#[test]
fn a_thumbnail_fits_the_box_preserves_aspect_and_never_enlarges() {
    // Wider than tall: width is the binding side.
    assert_eq!(thumbnail_size(1000, 500), (200, 100));
    // Taller than wide: height binds.
    assert_eq!(thumbnail_size(500, 1000), (140, 280));
    // Exactly the box.
    assert_eq!(thumbnail_size(200, 280), (200, 280));
    // Smaller than the box is left alone - RomM's own covers are 162x216, and
    // upscaling them would soften every one for nothing.
    assert_eq!(thumbnail_size(162, 216), (162, 216));
    assert_eq!(thumbnail_size(1, 1), (1, 1));
    // Never past the box on either side, whatever the ratio.
    for (width, height) in [(4000, 10), (10, 4000), (3000, 3000), (201, 281)] {
        let (scaled_width, scaled_height) = thumbnail_size(width, height);
        assert!(
            scaled_width <= THUMBNAIL_MAX_WIDTH && scaled_height <= THUMBNAIL_MAX_HEIGHT,
            "{width}x{height} became {scaled_width}x{scaled_height}"
        );
        assert!(
            scaled_width >= 1 && scaled_height >= 1,
            "nothing collapses to zero"
        );
        // The ratio is checked only where it can be expressed: 4000x10 scales to a
        // side under one pixel, and a one-pixel floor cannot also hold a 400:1
        // ratio. That is a rounding floor, not a stretch - what matters for those is
        // the bound above and the floor here.
        if scaled_width > 1 && scaled_height > 1 {
            let source_ratio = f64::from(width) / f64::from(height);
            let scaled_ratio = f64::from(scaled_width) / f64::from(scaled_height);
            assert!(
                (source_ratio - scaled_ratio).abs() / source_ratio < 0.02,
                "{width}x{height} -> {scaled_width}x{scaled_height} distorted the aspect ratio"
            );
        }
    }
}

#[test]
fn an_oversized_cover_is_downscaled_into_the_box() {
    let tree = Tree::new("downscale");
    let cache = tree.cache();
    let server = FakeArtworkServer::serving(synthetic_png(800, 1120));
    let thumbnail = cache
        .fetch(
            &source(),
            &server,
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");
    assert_eq!((thumbnail.width, thumbnail.height), (200, 280));
    // And what landed on disk really is that size, not just what the index claims.
    let stored = fs::read(&thumbnail.path).expect("thumbnail readable");
    assert_eq!(detect_format(&stored), Some(ImageFormat::Png));
    let width = u32::from_be_bytes(stored[16..20].try_into().expect("png header"));
    let height = u32::from_be_bytes(stored[20..24].try_into().expect("png header"));
    assert_eq!((width, height), (200, 280));
    assert!(
        stored.len() < 2 * 1024 * 1024,
        "a thumbnail must not be full-resolution artwork: {} bytes",
        stored.len()
    );
}

#[test]
fn thumbnail_output_is_deterministic() {
    let tree = Tree::new("deterministic");
    let cache = tree.cache();
    let png = synthetic_png(400, 560);
    let first = cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(png.clone()),
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");
    let first_bytes = fs::read(&first.path).expect("readable");

    let second_tree = Tree::new("deterministic-2");
    let second = second_tree
        .cache()
        .fetch(
            &source(),
            &FakeArtworkServer::serving(png),
            &request("1", Some("/assets/cover.png"), None),
            9_999,
            None,
        )
        .expect("stored");
    let second_bytes = fs::read(&second.path).expect("readable");
    assert_eq!(
        first_bytes, second_bytes,
        "the same cover must produce byte-identical thumbnails"
    );
}

// --- Cache keys and invalidation -----------------------------------------

#[test]
fn a_cache_key_is_deterministic_and_carries_no_secret() {
    let one = ArtworkCache::key_for(SERVER, &request("42", Some(REAL_SMALL_REFERENCE), None));
    let two = ArtworkCache::key_for(SERVER, &request("42", Some(REAL_SMALL_REFERENCE), None));
    assert_eq!(one, two, "the same request must key the same way");
    assert_eq!(one.len(), 32, "a 16-byte hex digest");
    assert!(one.chars().all(|c| c.is_ascii_hexdigit()));

    // Different record, different server, and a replaced cover all key differently.
    assert_ne!(
        one,
        ArtworkCache::key_for(SERVER, &request("43", Some(REAL_SMALL_REFERENCE), None))
    );
    assert_ne!(
        one,
        ArtworkCache::key_for(
            "http://10.0.0.5:8080",
            &request("42", Some(REAL_SMALL_REFERENCE), None)
        )
    );
    let replaced = "/assets/romm/resources/roms/149/1/cover/small.png?ts=2026-08-01 09:00:00";
    assert_ne!(
        one,
        ArtworkCache::key_for(SERVER, &request("42", Some(replaced), None)),
        "RomM's own timestamp changing must invalidate the thumbnail"
    );
}

#[test]
fn a_replaced_cover_is_refetched_rather_than_served_stale() {
    let tree = Tree::new("invalidate");
    let cache = tree.cache();
    let original = "/assets/cover.png?ts=1";
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some(original), None),
            1_000,
            None,
        )
        .expect("stored");
    assert!(
        cache
            .lookup(SERVER, &request("1", Some(original), None))
            .is_some()
    );

    // RomM rewrote the cover, so its timestamp moved.
    let replaced = "/assets/cover.png?ts=2";
    assert!(
        cache
            .lookup(SERVER, &request("1", Some(replaced), None))
            .is_none(),
        "the old thumbnail must not answer for the new cover"
    );
}

#[test]
fn an_index_from_another_server_is_not_reused() {
    let tree = Tree::new("other-server");
    let cache = tree.cache();
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");
    assert_eq!(cache.keys(SERVER).len(), 1);
    assert!(
        cache.keys("http://10.9.9.9:8080").is_empty(),
        "another instance's cache must start empty, as its identity records do"
    );
}

// --- Offline behaviour ---------------------------------------------------

#[test]
fn a_cached_thumbnail_is_served_offline_with_no_transport_at_all() {
    let tree = Tree::new("offline-hit");
    let cache = tree.cache();
    let wanted = request("1", Some(REAL_SMALL_REFERENCE), None);
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(162, 216)),
            &wanted,
            1_000,
            None,
        )
        .expect("stored");

    // `lookup` takes no transport, so offline browsing cannot make a request even
    // by accident.
    let hit = cache.lookup(SERVER, &wanted).expect("a cache hit");
    assert_eq!((hit.width, hit.height), (162, 216));
    assert!(hit.path.is_file());
}

#[test]
fn an_uncached_thumbnail_is_simply_absent_offline() {
    let tree = Tree::new("offline-miss");
    let cache = tree.cache();
    assert!(
        cache
            .lookup(SERVER, &request("999", Some("/assets/cover.png"), None))
            .is_none(),
        "a miss is a placeholder, not an error and not a request"
    );
}

#[test]
fn a_thumbnail_whose_file_has_been_corrupted_is_dropped_and_refetched() {
    let tree = Tree::new("corrupt-on-disk");
    let cache = tree.cache();
    let wanted = request("1", Some("/assets/cover.png"), None);
    let stored = cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &wanted,
            1_000,
            None,
        )
        .expect("stored");

    // Something outside EmuWiz damaged the file.
    fs::write(&stored.path, b"not a png any more").expect("fixture");
    assert!(
        cache.lookup(SERVER, &wanted).is_none(),
        "a corrupt thumbnail must not be drawn"
    );
    assert!(
        !stored.path.exists(),
        "and it should be removed so the next request refetches"
    );
    assert!(
        cache.keys(SERVER).is_empty(),
        "the index should have forgotten it too"
    );

    // Refetching works.
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &wanted,
            2_000,
            None,
        )
        .expect("refetched");
    assert!(cache.lookup(SERVER, &wanted).is_some());
}

// --- Bounded cache: accounting, eviction, clearing -----------------------

#[test]
fn the_cache_reports_its_size_count_and_ceiling() {
    let tree = Tree::new("stats");
    let cache = tree.cache();
    let empty = cache.stats(SERVER);
    assert_eq!(empty.items, 0);
    assert_eq!(empty.bytes, 0);
    assert_eq!(empty.maximum_bytes, MAX_CACHE_BYTES);
    assert_eq!(empty.maximum_bytes, 1024 * 1024 * 1024, "one gibibyte");
    assert!(empty.last_cleanup_unix_seconds.is_none());

    for index in 0..3 {
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(60, 84)),
                &request(&format!("{index}"), Some("/assets/cover.png"), None),
                1_000,
                None,
            )
            .expect("stored");
    }
    let filled = cache.stats(SERVER);
    assert_eq!(filled.items, 3);
    assert!(filled.bytes > 0);
    assert_eq!(filled.format_version, ARTWORK_FORMAT_VERSION);
    assert!(filled.directory.ends_with("artwork"));
}

#[test]
fn eviction_removes_the_least_recently_used_first() {
    let tree = Tree::new("eviction");
    let cache = tree.cache();
    // Three entries, used at increasing times.
    for (index, used_at) in [("a", 1_000), ("b", 2_000), ("c", 3_000)] {
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(index, Some(&format!("/assets/{index}.png")), None),
                used_at,
                None,
            )
            .expect("stored");
    }
    let before = cache.stats(SERVER);
    assert_eq!(before.items, 3);

    // A ceiling that only two of them fit under.
    let per_item = before.bytes / 3;
    let outcome = cache.evict_to_limit(SERVER, per_item * 2, 9_000);
    assert_eq!(outcome.evicted_items, 1, "{outcome:?}");
    assert!(outcome.bytes_after <= per_item * 2);

    let remaining = cache.keys(SERVER);
    assert_eq!(remaining.len(), 2);
    // The oldest use - "a" - is the one that went.
    let oldest = ArtworkCache::key_for(SERVER, &request("a", Some("/assets/a.png"), None));
    assert!(
        !remaining.contains(&oldest),
        "the least recently used entry should have been evicted"
    );
    // Its file went with it, so the accounting and the disk agree.
    assert_eq!(
        fs::read_dir(cache.directory().join(THUMBNAIL_DIRECTORY_NAME))
            .expect("thumbnails")
            .count(),
        2
    );
    assert_eq!(cache.stats(SERVER).last_cleanup_unix_seconds, Some(9_000));
}

#[test]
fn eviction_is_deterministic_when_times_tie() {
    let build = |label: &str| {
        let tree = Tree::new(label);
        let cache = tree.cache();
        for index in 0..4 {
            cache
                .fetch(
                    &source(),
                    &FakeArtworkServer::serving(synthetic_png(40, 56)),
                    &request(&format!("{index}"), Some(&format!("/a/{index}.png")), None),
                    1_000,
                    None,
                )
                .expect("stored");
        }
        (tree, cache)
    };
    let (_first_tree, first_cache) = build("eviction-ties");
    let bytes = first_cache.stats(SERVER).bytes;
    let first = first_cache.evict_to_limit(SERVER, bytes / 2, 5_000);

    let (_second_tree, second_cache) = build("eviction-ties-2");
    let repeat = second_cache.evict_to_limit(SERVER, bytes / 2, 5_000);
    assert_eq!(first.evicted_items, repeat.evicted_items);
    assert_eq!(second_cache.keys(SERVER), first_cache.keys(SERVER));
}

#[test]
fn storing_keeps_the_cache_inside_its_ceiling() {
    let tree = Tree::new("ceiling-on-write");
    let cache = tree.cache();
    // Every store evicts down to the ceiling, so the cache cannot exceed it
    // between explicit cleanups.
    for index in 0..5 {
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(&format!("{index}"), Some(&format!("/a/{index}.png")), None),
                1_000 + i64::from(index),
                None,
            )
            .expect("stored");
        assert!(
            cache.stats(SERVER).bytes <= MAX_CACHE_BYTES,
            "the cache grew past its ceiling"
        );
    }
}

#[test]
fn a_recorded_use_only_rewrites_the_index_when_it_has_drifted() {
    let tree = Tree::new("touch");
    let cache = tree.cache();
    let wanted = request("1", Some("/assets/cover.png"), None);
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &wanted,
            1_000,
            None,
        )
        .expect("stored");
    let key = ArtworkCache::key_for(SERVER, &wanted);

    // A use moments later changes nothing on disk: a scrolling grid must not write
    // the index every frame.
    let before = fs::read(cache.directory().join(INDEX_FILE_NAME)).expect("index");
    cache.touch(SERVER, &key, 1_010);
    let after = fs::read(cache.directory().join(INDEX_FILE_NAME)).expect("index");
    assert_eq!(before, after, "a near-instant re-use should not rewrite");

    // A use well past the interval does.
    cache.touch(SERVER, &key, 1_000 + LAST_USED_WRITE_INTERVAL_SECONDS + 1);
    let later = fs::read(cache.directory().join(INDEX_FILE_NAME)).expect("index");
    assert_ne!(before, later, "a much later use should be recorded");
}

#[test]
fn clearing_needs_confirmation_and_leaves_the_identity_cache_alone() {
    let tree = Tree::new("clear");
    let cache = tree.cache();
    // Something that must survive, written where the identity cache lives.
    let identity_file = tree
        .identity()
        .join(IdentityProvider::Romm.slug())
        .join("identity-cache.json");
    fs::create_dir_all(identity_file.parent().expect("parent")).expect("fixture");
    fs::write(&identity_file, b"{\"records\":[]}").expect("fixture");

    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");

    assert!(
        cache.clear(SERVER, false).is_err(),
        "clearing must be confirmed"
    );
    assert_eq!(cache.stats(SERVER).items, 1, "and nothing removed");

    let outcome = cache.clear(SERVER, true).expect("cleared");
    assert_eq!(outcome.removed_items, 1);
    assert!(outcome.removed_bytes > 0);
    assert!(!outcome.identity_cache_touched);
    assert_eq!(cache.stats(SERVER).items, 0);
    assert!(
        identity_file.is_file(),
        "the identity cache must be untouched by a thumbnail clear"
    );
    assert_eq!(
        fs::read(&identity_file).expect("readable"),
        b"{\"records\":[]}",
        "and unchanged"
    );
}

#[test]
fn a_clear_during_an_in_flight_fetch_leaves_a_consistent_cache() {
    let tree = Tree::new("clear-race");
    let cache = tree.cache();
    let wanted = request("1", Some("/assets/cover.png"), None);
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &wanted,
            1_000,
            None,
        )
        .expect("stored");

    // The clear lands, and then a fetch that was already running publishes. The
    // result must be a cache that agrees with itself: the new entry present, and
    // nothing claiming a file that is not there.
    cache.clear(SERVER, true).expect("cleared");
    let after = cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(50, 70)),
            &request("2", Some("/assets/two.png"), None),
            2_000,
            None,
        )
        .expect("the late publication should still succeed");
    assert!(after.path.is_file());
    let keys = cache.keys(SERVER);
    assert_eq!(keys.len(), 1, "only the late entry survives: {keys:?}");
    for key in keys {
        assert!(
            cache
                .directory()
                .join(THUMBNAIL_DIRECTORY_NAME)
                .join(format!("{key}.png"))
                .is_file(),
            "every indexed entry must have its file"
        );
    }
}

#[test]
fn an_interrupted_write_leaves_no_temporary_file_behind() {
    let tree = Tree::new("temp-files");
    let cache = tree.cache();
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");
    // Simulate an interruption having left one behind.
    let stray = cache
        .directory()
        .join(THUMBNAIL_DIRECTORY_NAME)
        .join("abcdef.999.tmp");
    fs::write(&stray, b"partial").expect("fixture");
    assert_eq!(clean_temporary_files(&cache), 1);
    assert!(!stray.exists());
    // The real entry is untouched.
    assert_eq!(cache.stats(SERVER).items, 1);
}

#[test]
fn the_index_holds_no_url_and_no_credential() {
    let tree = Tree::new("index-secrets");
    let cache = tree.cache();
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some(REAL_SMALL_REFERENCE), None),
            1_000,
            None,
        )
        .expect("stored");
    let index = fs::read_to_string(cache.directory().join(INDEX_FILE_NAME)).expect("index");
    assert!(
        !index.contains(FIXTURE_TOKEN),
        "the token must not reach the index"
    );
    assert!(!index.to_lowercase().contains("bearer"), "{index}");
    // The approved origin is there deliberately - it is what keeps one instance's
    // thumbnails from answering for another's, and it is already in config.json.
    // What must not be there is a cover path or query.
    assert!(index.contains(SERVER), "the server identity is expected");
    assert!(
        !index.contains("/assets/"),
        "no cover path belongs in the index: {index}"
    );
    assert!(
        !index.contains("ts=") && !index.contains("small.png"),
        "no cover query or filename either: {index}"
    );
    // The filenames carry no secret either.
    for key in cache.keys(SERVER) {
        assert!(key.chars().all(|c| c.is_ascii_hexdigit()), "{key}");
    }
}

#[test]
fn an_index_written_by_a_newer_version_is_discarded_not_misread() {
    let tree = Tree::new("index-version");
    let cache = tree.cache();
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("1", Some("/assets/cover.png"), None),
            1_000,
            None,
        )
        .expect("stored");

    let path = cache.directory().join(INDEX_FILE_NAME);
    let text = fs::read_to_string(&path).expect("index");
    fs::write(
        &path,
        text.replace(
            &format!("\"format_version\": {ARTWORK_FORMAT_VERSION}"),
            "\"format_version\": 99",
        ),
    )
    .expect("fixture");
    assert_eq!(
        cache.stats(SERVER).items,
        0,
        "a future layout is started again from empty, since thumbnails are derived"
    );
}

// --- Concurrent index updates --------------------------------------------
//
// The index is one shared file and the cache has several callers: the Gamer View
// list resolves covers on its own worker while the Details panel and the record
// browser resolve theirs through the GUI's operation queue, and the CLI can be
// working over the same directory. Before every modification went through
// `update_index`, two callers could each read the index, add their own entry and
// rename their own version over the file - the rename is atomic so the file was
// never torn, but the second writer silently reverted the first.
//
// Each test here constructs a *separate* `ArtworkCache` per thread, because that is
// what the real callers do: nothing shares one instance, so anything that made
// these pass by sharing state within a single object would be testing a fiction.

/// Runs `count` closures at once, released together so they collide.
fn in_parallel(count: usize, body: impl Fn(usize) + Send + Sync + 'static) {
    let barrier = std::sync::Arc::new(std::sync::Barrier::new(count));
    let body = std::sync::Arc::new(body);
    let handles: Vec<_> = (0..count)
        .map(|index| {
            let barrier = std::sync::Arc::clone(&barrier);
            let body = std::sync::Arc::clone(&body);
            std::thread::spawn(move || {
                barrier.wait();
                body(index);
            })
        })
        .collect();
    for handle in handles {
        handle.join().expect("a worker panicked");
    }
}

#[test]
fn two_concurrent_writers_adding_different_entries_keep_both() {
    let tree = Tree::new("concurrent-insert");
    let root = tree.identity();

    in_parallel(2, move |index| {
        // A fresh cache per thread, exactly as the GUI's three call sites build one.
        let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(
                    &format!("game-{index}"),
                    Some(&format!("/assets/{index}.png")),
                    None,
                ),
                1_000,
                None,
            )
            .expect("stored");
    });

    let cache = tree.cache();
    assert_eq!(
        cache.keys(SERVER).len(),
        2,
        "one writer's entry was lost: {:?}",
        cache.keys(SERVER)
    );
}

#[test]
fn many_concurrent_writers_all_keep_their_entries() {
    let tree = Tree::new("concurrent-insert-many");
    let root = tree.identity();
    const WRITERS: usize = 12;

    in_parallel(WRITERS, move |index| {
        let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(
                    &format!("game-{index}"),
                    Some(&format!("/assets/{index}.png")),
                    None,
                ),
                1_000,
                None,
            )
            .expect("stored");
    });

    let cache = tree.cache();
    let keys = cache.keys(SERVER);
    assert_eq!(keys.len(), WRITERS, "entries were lost: {keys:?}");
    // Every recorded entry still has the file it describes.
    assert_eq!(
        fs::read_dir(cache.directory().join(THUMBNAIL_DIRECTORY_NAME))
            .expect("thumbnails")
            .count(),
        WRITERS
    );
}

#[test]
fn updating_one_entry_while_another_is_inserted_keeps_both() {
    let tree = Tree::new("concurrent-touch-insert");
    let root = tree.identity();
    // An entry that already exists, whose recorded use is old enough to rewrite.
    let existing = request("existing", Some("/assets/existing.png"), None);
    let existing_key = ArtworkCache::key_for(SERVER, &existing);
    tree.cache()
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &existing,
            1_000,
            None,
        )
        .expect("stored");

    let touch_key = existing_key.clone();
    in_parallel(2, move |index| {
        let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
        if index == 0 {
            // Well past the write interval, so this really does rewrite the index.
            cache.touch(
                SERVER,
                &touch_key,
                1_000 + LAST_USED_WRITE_INTERVAL_SECONDS * 2,
            );
        } else {
            cache
                .fetch(
                    &source(),
                    &FakeArtworkServer::serving(synthetic_png(40, 56)),
                    &request("added", Some("/assets/added.png"), None),
                    2_000,
                    None,
                )
                .expect("stored");
        }
    });

    let cache = tree.cache();
    let keys = cache.keys(SERVER);
    assert_eq!(keys.len(), 2, "an entry was lost: {keys:?}");
    assert!(keys.contains(&existing_key), "the touched entry vanished");
    // And the touch was not reverted by the insert.
    let entries = index_entries(&cache, SERVER);
    let touched = entries
        .iter()
        .find(|entry| entry.key == existing_key)
        .expect("the touched entry");
    assert_eq!(
        touched.last_used_unix_seconds,
        1_000 + LAST_USED_WRITE_INTERVAL_SECONDS * 2,
        "the recorded use was reverted by the concurrent insert"
    );
}

#[test]
fn a_gamer_view_load_and_an_explicit_detail_load_both_survive() {
    // The exact pairing the GUI produces: the Gamer View worker resolving a row's
    // cover at the same moment someone presses Show cover in the Details panel.
    // Both go through `ArtworkCache`, from different threads, with their own
    // instances - and neither may erase the other's entry.
    let tree = Tree::new("concurrent-gamer-and-details");
    let root = tree.identity();

    in_parallel(2, move |index| {
        let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
        let (id, reference) = if index == 0 {
            (
                "gamer-view-row",
                "/assets/romm/resources/roms/149/1/cover/small.png?ts=1",
            )
        } else {
            (
                "details-panel",
                "/assets/romm/resources/roms/149/2/cover/small.png?ts=2",
            )
        };
        cache
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(162, 216)),
                &request(id, Some(reference), None),
                3_000,
                None,
            )
            .expect("stored");
    });

    let cache = tree.cache();
    for id in ["gamer-view-row", "details-panel"] {
        let reference = if id == "gamer-view-row" {
            "/assets/romm/resources/roms/149/1/cover/small.png?ts=1"
        } else {
            "/assets/romm/resources/roms/149/2/cover/small.png?ts=2"
        };
        let wanted = request(id, Some(reference), None);
        assert!(
            cache.lookup(SERVER, &wanted).is_some(),
            "{id}'s thumbnail was lost to the other caller"
        );
    }
}

#[test]
fn repeated_concurrent_operations_leave_parseable_json() {
    let tree = Tree::new("concurrent-json");
    let root = tree.identity();

    for round in 0..6 {
        let root = root.clone();
        in_parallel(6, move |index| {
            let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
            let id = format!("r{round}-{index}");
            cache
                .fetch(
                    &source(),
                    &FakeArtworkServer::serving(synthetic_png(40, 56)),
                    &request(&id, Some(&format!("/assets/{id}.png")), None),
                    4_000 + round as i64,
                    None,
                )
                .expect("stored");
            // Reads and evictions run alongside the writes.
            let _ = cache.stats(SERVER);
            let _ = cache.evict_to_limit(SERVER, MAX_CACHE_BYTES, 4_000);
        });
    }

    // The file itself must still be an index, not a fragment of one.
    let text = fs::read_to_string(tree.cache().directory().join(INDEX_FILE_NAME))
        .expect("the index should still be readable");
    let parsed: ArtworkIndex =
        serde_json::from_str(&text).expect("the index should still be valid JSON");
    assert_eq!(parsed.format_version, ARTWORK_FORMAT_VERSION);
    assert_eq!(parsed.server_id, SERVER);
    assert_eq!(parsed.entries.len(), 36, "entries were lost across rounds");
    // No duplicate keys: every writer merged rather than appended blindly.
    let mut keys: Vec<&str> = parsed.entries.iter().map(|e| e.key.as_str()).collect();
    keys.sort_unstable();
    let before = keys.len();
    keys.dedup();
    assert_eq!(before, keys.len(), "the index holds duplicate keys");
}

#[test]
fn a_failed_index_write_leaves_the_previous_index_readable() {
    let tree = Tree::new("failed-write");
    let cache = tree.cache();
    cache
        .fetch(
            &source(),
            &FakeArtworkServer::serving(synthetic_png(40, 56)),
            &request("kept", Some("/assets/kept.png"), None),
            1_000,
            None,
        )
        .expect("stored");
    let before = fs::read_to_string(cache.directory().join(INDEX_FILE_NAME)).expect("index");
    let keys_before = cache.keys(SERVER);

    // The index path is made into a directory, so the rename that publishes a new
    // index cannot succeed. The previous bytes are what a reader must still get.
    fs::remove_file(cache.directory().join(INDEX_FILE_NAME)).expect("remove");
    let index_path = cache.directory().join(INDEX_FILE_NAME);
    fs::create_dir(&index_path).expect("occupy the index path");

    let refused = cache.fetch(
        &source(),
        &FakeArtworkServer::serving(synthetic_png(40, 56)),
        &request("doomed", Some("/assets/doomed.png"), None),
        2_000,
        None,
    );
    assert!(
        matches!(refused, Err(ArtworkRefusal::WriteFailed { .. })),
        "a failed index write should be reported: {refused:?}"
    );
    // No half-written index and no stray temporary file left behind.
    let strays: Vec<_> = fs::read_dir(cache.directory())
        .expect("directory")
        .flatten()
        .filter(|entry| entry.path().extension().and_then(|value| value.to_str()) == Some("tmp"))
        .collect();
    assert!(strays.is_empty(), "a temporary index file was left behind");

    // Put the real index back: it was never modified, so it still reads.
    fs::remove_dir(&index_path).expect("free the index path");
    fs::write(&index_path, &before).expect("restore");
    assert_eq!(
        cache.keys(SERVER),
        keys_before,
        "the previous index no longer describes what it did"
    );
}

#[test]
fn concurrent_eviction_and_insertion_leave_the_cache_inside_its_ceiling() {
    // Eviction decides what to remove from the index it reads. Under the lock that
    // is the latest one, so it cannot delete a thumbnail another caller recorded a
    // moment earlier and then leave the index claiming it is still there.
    let tree = Tree::new("concurrent-evict");
    let root = tree.identity();
    for index in 0..4 {
        tree.cache()
            .fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(
                    &format!("seed-{index}"),
                    Some(&format!("/a/{index}.png")),
                    None,
                ),
                1_000 + index,
                None,
            )
            .expect("stored");
    }
    let ceiling = tree.cache().stats(SERVER).bytes / 2;

    in_parallel(4, move |index| {
        let cache = ArtworkCache::new(&root, IdentityProvider::Romm);
        if index % 2 == 0 {
            let _ = cache.evict_to_limit(SERVER, ceiling, 9_000);
        } else {
            let _ = cache.fetch(
                &source(),
                &FakeArtworkServer::serving(synthetic_png(40, 56)),
                &request(
                    &format!("late-{index}"),
                    Some(&format!("/b/{index}.png")),
                    None,
                ),
                9_000,
                None,
            );
        }
    });

    let cache = tree.cache();
    let entries = index_entries(&cache, SERVER);
    // Every entry the index claims must have a file, and every file must be claimed.
    let files: std::collections::HashSet<String> =
        fs::read_dir(cache.directory().join(THUMBNAIL_DIRECTORY_NAME))
            .expect("thumbnails")
            .flatten()
            .filter_map(|entry| {
                entry
                    .path()
                    .file_stem()
                    .and_then(|stem| stem.to_str())
                    .map(str::to_string)
            })
            .collect();
    for entry in &entries {
        assert!(
            files.contains(&entry.key),
            "the index claims {} but its thumbnail is gone",
            entry.key
        );
    }
    assert_eq!(
        files.len(),
        entries.len(),
        "an orphaned thumbnail was left behind"
    );
}
