//! Turning one chosen candidate and one cheat selection into a real,
//! installable RetroArch cheat file.
//!
//! This is the step that was missing between the catalogue (read-only) and
//! the shared apply/rollback machinery (which installs *files*, by digest,
//! from an approved source root). Previously the only thing RetroArch cheat
//! installation could do was copy a whole catalogue file verbatim; there was
//! no way to install a chosen subset, because the catalogue parser never
//! kept the cheat codes.
//!
//! The pipeline here is:
//!
//! 1. [`load_candidate_document`] - re-read the chosen candidate from the
//!    verified catalogue root, confirm its digest still matches the one the
//!    candidate list was built from, and parse it with [`super::cht_document`].
//! 2. [`CheatSelection`] - the user's per-cheat choices, which can never
//!    include an entry the parser marked unsafe.
//! 3. [`resolve_cheat_destination`] - the real destination inside the
//!    selected profile's own cheat directory, named from the strongest
//!    available identity, refusing anything that is not provably inside
//!    that directory.
//! 4. [`stage_generated_cheat_file`] - render the file deterministically and
//!    write it into a private staging root, which then acts as the
//!    "approved source root" the existing transaction machinery already
//!    understands.
//! 5. [`build_cheat_install_preview`] - hand that staged file to
//!    [`build_shared_preview`], so backup, atomic write, verification,
//!    journalling, and rollback are the *same* code paths every other
//!    adapter uses rather than a second implementation.
//!
//! The trusted catalogue is only ever read. Nothing in this module writes,
//! renames, or deletes anything under the catalogue root.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::Serialize;
use sha2::{Digest, Sha256};

use super::cheat_candidates::CheatCandidate;
use super::cht_document::{
    ChtDocument, ChtEntry, ChtInstallEntry, ChtParseErrorKind, parse_cht_bytes, render_cht_file,
};
use super::destination_safety::{DestinationSafetyError, DestinationState, assess_destination};
use super::shared_preview::{
    PreviewAdapter, PreviewIdentity, PreviewIdentityKind, PreviewIdentityState,
    PreviewMatchStrength, PreviewSourceItem, SharedPreviewError, SharedPreviewReport,
    SharedPreviewRequest, build_shared_preview,
};
use crate::canonical_platform_for_alias;

/// Mirrors `cheat_catalogue::MAX_CATALOGUE_FILE_BYTES`.
pub const MAX_CANDIDATE_FILE_BYTES: u64 = 8 * 1024 * 1024;
/// A generated file is only ever a subset of a candidate, so it is bounded
/// by the same figure.
pub const MAX_GENERATED_FILE_BYTES: usize = 8 * 1024 * 1024;
/// The comment written at the top of every generated file. Fixed text, with
/// no timestamp or host detail, so output stays deterministic and carries
/// no environment information into the emulator's directory.
/// Existing platform-directory names examined in one cheat root.
pub const MAX_PLATFORM_DIRECTORY_CANDIDATES: usize = 512;
pub const GENERATED_FILE_PROVENANCE: &str =
    "Generated by EmuWiz from a verified trusted cheat catalogue.";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CheatInstallPlanErrorKind {
    /// The candidate path escapes the catalogue root, or is not a single
    /// safe relative path.
    CandidatePathUnsafe,
    CandidateMissing,
    CandidateUnreadable,
    CandidateTooLarge,
    /// The file changed on disk since the candidate list was built.
    CandidateDigestMismatch,
    CandidateUnsupportedEncoding,
    CandidateMalformed,
    /// The candidate is not one the candidate list marked installable.
    CandidateNotInstallable,
    /// Nothing was selected, or everything selected was unsafe.
    NoSelectedCheats,
    /// A selected entry does not exist in the candidate, or is unsafe.
    SelectionInvalid,
    /// The profile declares no usable cheat directory.
    DestinationRootUnavailable,
    /// The platform could not be resolved to a canonical directory name.
    DestinationPlatformUnresolved,
    /// No usable filename could be derived from any available identity.
    DestinationNameUnresolved,
    /// The destination is a symlink, escapes the root, or is otherwise
    /// unsafe. Carries the underlying [`DestinationSafetyError`] reason.
    DestinationUnsafe,
    StagingUnavailable,
    GeneratedFileTooLarge,
    PreviewFailed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CheatInstallPlanError {
    pub kind: CheatInstallPlanErrorKind,
    pub path: Option<PathBuf>,
    pub detail: String,
}

impl std::fmt::Display for CheatInstallPlanError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.detail)
    }
}

impl std::error::Error for CheatInstallPlanError {}

fn error(
    kind: CheatInstallPlanErrorKind,
    path: Option<&Path>,
    detail: impl Into<String>,
) -> CheatInstallPlanError {
    CheatInstallPlanError {
        kind,
        path: path.map(Path::to_path_buf),
        detail: detail.into(),
    }
}

// ---------------------------------------------------------------------
// 1. Loading the chosen candidate
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadedCandidate {
    pub absolute_path: PathBuf,
    /// SHA-256 of the exact bytes parsed.
    pub digest: String,
    pub document: ChtDocument,
}

/// Re-reads and parses one candidate from the verified catalogue root.
///
/// The candidate's relative path is validated component by component: an
/// absolute path, a `..` component, or anything that does not land inside
/// the catalogue root is rejected before the file is opened, so a candidate
/// identity that was tampered with in transit cannot address another file.
///
/// `expected_digest` is the digest the candidate list recorded. A mismatch
/// means the catalogue changed underneath the user's choice, and is an
/// error rather than a silent re-selection.
pub fn load_candidate_document(
    catalogue_root: &Path,
    relative_path: &str,
    expected_digest: Option<&str>,
) -> Result<LoadedCandidate, CheatInstallPlanError> {
    let absolute = resolve_catalogue_relative_path(catalogue_root, relative_path)?;

    let metadata = fs::symlink_metadata(&absolute).map_err(|failure| {
        let kind = if failure.kind() == std::io::ErrorKind::NotFound {
            CheatInstallPlanErrorKind::CandidateMissing
        } else {
            CheatInstallPlanErrorKind::CandidateUnreadable
        };
        error(
            kind,
            Some(&absolute),
            format!("candidate unreadable: {failure}"),
        )
    })?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(error(
            CheatInstallPlanErrorKind::CandidatePathUnsafe,
            Some(&absolute),
            "candidate is a symlink or not a regular file; it is never followed",
        ));
    }
    if metadata.len() > MAX_CANDIDATE_FILE_BYTES {
        return Err(error(
            CheatInstallPlanErrorKind::CandidateTooLarge,
            Some(&absolute),
            format!("candidate exceeds {MAX_CANDIDATE_FILE_BYTES} bytes"),
        ));
    }

    let bytes = fs::read(&absolute).map_err(|failure| {
        error(
            CheatInstallPlanErrorKind::CandidateUnreadable,
            Some(&absolute),
            format!("candidate could not be read: {failure}"),
        )
    })?;
    let digest = hex_sha256(&bytes);
    if let Some(expected) = expected_digest
        && !expected.eq_ignore_ascii_case(&digest)
    {
        return Err(error(
            CheatInstallPlanErrorKind::CandidateDigestMismatch,
            Some(&absolute),
            "candidate file changed since it was matched; re-run matching before installing",
        ));
    }

    let document = parse_cht_bytes(&bytes).map_err(|failure| {
        let kind = match failure.kind {
            ChtParseErrorKind::UnsupportedEncoding
            | ChtParseErrorKind::UnsupportedUtf16Encoding => {
                CheatInstallPlanErrorKind::CandidateUnsupportedEncoding
            }
            ChtParseErrorKind::NotACheatFile | ChtParseErrorKind::TooManyEntries => {
                CheatInstallPlanErrorKind::CandidateMalformed
            }
        };
        error(kind, Some(&absolute), failure.detail)
    })?;

    Ok(LoadedCandidate {
        absolute_path: absolute,
        digest,
        document,
    })
}

/// Joins a catalogue-relative path onto the root, refusing anything that is
/// not a plain relative path of ordinary components.
fn resolve_catalogue_relative_path(
    catalogue_root: &Path,
    relative_path: &str,
) -> Result<PathBuf, CheatInstallPlanError> {
    use std::path::Component;

    if relative_path.trim().is_empty() {
        return Err(error(
            CheatInstallPlanErrorKind::CandidatePathUnsafe,
            Some(catalogue_root),
            "candidate path is empty",
        ));
    }
    let relative = Path::new(relative_path);
    if relative.is_absolute() {
        return Err(error(
            CheatInstallPlanErrorKind::CandidatePathUnsafe,
            Some(relative),
            "candidate path must be relative to the catalogue root",
        ));
    }
    let mut absolute = catalogue_root.to_path_buf();
    for component in relative.components() {
        match component {
            Component::Normal(value) => absolute.push(value),
            _ => {
                return Err(error(
                    CheatInstallPlanErrorKind::CandidatePathUnsafe,
                    Some(relative),
                    "candidate path contains a traversal or root component",
                ));
            }
        }
    }
    if !absolute.starts_with(catalogue_root) {
        return Err(error(
            CheatInstallPlanErrorKind::CandidatePathUnsafe,
            Some(&absolute),
            "candidate path resolves outside the catalogue root",
        ));
    }
    Ok(absolute)
}

// ---------------------------------------------------------------------
// 2. Individual cheat selection
// ---------------------------------------------------------------------

/// One row of the cheat picker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CheatSelectionEntry {
    /// The source `cheatN_` index. Stable across re-renders, and the key the
    /// GUI uses when toggling.
    pub source_index: u32,
    pub description: String,
    /// Whether this entry may be ticked at all.
    pub selectable: bool,
    /// Whether it is currently ticked - i.e. included in the installed file.
    pub selected: bool,
    /// Whether RetroArch should have it *active* on load. Meaningless when
    /// `selected` is false.
    pub enabled: bool,
    /// Human-readable warnings from the parser, blocking ones first.
    pub warnings: Vec<String>,
    pub has_blocking_warning: bool,
}

/// The whole picker state for one candidate. Construction never selects
/// anything: "no cheats chosen yet" is a real state a user must resolve,
/// not something to guess past by ticking every box.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CheatSelection {
    pub entries: Vec<CheatSelectionEntry>,
}

impl CheatSelection {
    /// Builds the picker in catalogue order. Nothing is selected; each
    /// entry's `enabled` starts at the source's own `cheatN_enable`, so
    /// ticking a cheat preserves what the catalogue author intended rather
    /// than forcing a project-wide default.
    #[must_use]
    pub fn from_document(document: &ChtDocument) -> Self {
        Self {
            entries: document.entries.iter().map(entry_row).collect(),
        }
    }

    #[must_use]
    pub fn selected_count(&self) -> usize {
        self.entries.iter().filter(|entry| entry.selected).count()
    }

    #[must_use]
    pub fn selectable_count(&self) -> usize {
        self.entries.iter().filter(|entry| entry.selectable).count()
    }

    #[must_use]
    pub fn blocked_count(&self) -> usize {
        self.entries
            .iter()
            .filter(|entry| !entry.selectable)
            .count()
    }

    /// Apply is only available with at least one valid selected cheat.
    #[must_use]
    pub fn can_apply(&self) -> bool {
        self.selected_count() > 0
    }

    /// Ticks one entry. Returns false - changing nothing - when the entry
    /// does not exist or is unsafe, so an unsafe entry can never become
    /// selected through any code path.
    pub fn set_selected(&mut self, source_index: u32, selected: bool) -> bool {
        let Some(entry) = self
            .entries
            .iter_mut()
            .find(|entry| entry.source_index == source_index)
        else {
            return false;
        };
        if selected && !entry.selectable {
            return false;
        }
        entry.selected = selected;
        true
    }

    /// Sets whether a selected cheat starts active in RetroArch.
    pub fn set_enabled(&mut self, source_index: u32, enabled: bool) -> bool {
        let Some(entry) = self
            .entries
            .iter_mut()
            .find(|entry| entry.source_index == source_index && entry.selectable)
        else {
            return false;
        };
        entry.enabled = enabled;
        true
    }

    /// Selects every *selectable* entry. Blocked entries stay untouched.
    pub fn select_all(&mut self) {
        for entry in &mut self.entries {
            if entry.selectable {
                entry.selected = true;
            }
        }
    }

    pub fn clear_all(&mut self) {
        for entry in &mut self.entries {
            entry.selected = false;
        }
    }

    /// The selected entries, in catalogue order, resolved against the
    /// document they came from. Returns an error rather than silently
    /// dropping a selection that no longer resolves.
    pub fn resolve(
        &self,
        document: &ChtDocument,
    ) -> Result<Vec<ChtInstallEntry>, CheatInstallPlanError> {
        let mut resolved = Vec::new();
        for row in self.entries.iter().filter(|entry| entry.selected) {
            let entry = document.entry(row.source_index).ok_or_else(|| {
                error(
                    CheatInstallPlanErrorKind::SelectionInvalid,
                    None,
                    format!(
                        "selected cheat {} is not in the candidate",
                        row.source_index
                    ),
                )
            })?;
            let install = ChtInstallEntry::from_entry(entry, row.enabled).ok_or_else(|| {
                error(
                    CheatInstallPlanErrorKind::SelectionInvalid,
                    None,
                    format!("selected cheat {} is not safe to install", row.source_index),
                )
            })?;
            resolved.push(install);
        }
        if resolved.is_empty() {
            return Err(error(
                CheatInstallPlanErrorKind::NoSelectedCheats,
                None,
                "no cheats are selected; choose at least one before applying",
            ));
        }
        Ok(resolved)
    }
}

fn entry_row(entry: &ChtEntry) -> CheatSelectionEntry {
    let mut warnings: Vec<&super::cht_document::ChtEntryWarning> = entry.warnings.iter().collect();
    warnings.sort_by_key(|warning| !warning.kind.is_blocking());
    CheatSelectionEntry {
        source_index: entry.index,
        description: entry.effective_description(),
        selectable: entry.is_selectable(),
        selected: false,
        enabled: entry.enabled_by_default,
        warnings: warnings
            .iter()
            .map(|warning| warning.detail.clone())
            .collect(),
        has_blocking_warning: entry.blocking_warnings().next().is_some(),
    }
}

// ---------------------------------------------------------------------
// 3. Destination resolution
// ---------------------------------------------------------------------

/// Which identity the installed filename was taken from. Always reported,
/// never guessed silently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CheatDestinationNameSource {
    /// The content file's own basename - what RetroArch shows as the
    /// content name, and therefore the name it looks for.
    ContentBasename,
    /// The playlist/database label for this content.
    PlaylistName,
    /// The catalogue file's own name, used only when nothing stronger is
    /// available.
    CatalogueName,
}

impl CheatDestinationNameSource {
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::ContentBasename => "content filename",
            Self::PlaylistName => "playlist entry name",
            Self::CatalogueName => "catalogue file name",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CheatDestinationRequest {
    /// The selected profile's own resolved cheat directory. Never a default
    /// this module invents.
    pub profile_cheat_root: PathBuf,
    /// Exact RetroArch core directory identifier. When supplied, the
    /// destination is `<cheat root>/<core>/<content>.cht`; absence retains
    /// the legacy platform-directory behavior for non-RetroArch callers.
    pub retroarch_core: Option<String>,
    /// Require an exact core for RetroArch automatic placement; when true,
    /// an absent core fails closed instead of using the legacy layout.
    pub retroarch_core_required: bool,
    /// The archive's platform, in any recognized spelling.
    pub platform: Option<String>,
    /// The content file's basename without extension.
    pub content_basename: Option<String>,
    /// The playlist/database label, when one is known.
    pub playlist_name: Option<String>,
    /// The chosen candidate's own display name.
    pub catalogue_name: String,
}

/// Where the platform subdirectory name came from. A real RetroArch cheat
/// directory is laid out by libretro *database* name ("Nintendo - Nintendo
/// Entertainment System"), not by this project's canonical short name
/// ("NES"), so which one was used has to be visible.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CheatPlatformDirectorySource {
    /// A directory that already exists in the profile's cheat root and
    /// resolves to this same platform - the layout RetroArch itself ships
    /// and the user already browses.
    ExistingProfileDirectory,
    /// No matching directory exists yet, so the canonical platform name is
    /// used and the directory is created.
    CanonicalPlatformName,
}

impl CheatPlatformDirectorySource {
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::ExistingProfileDirectory => "existing RetroArch cheat directory",
            Self::CanonicalPlatformName => "canonical platform name (new directory)",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedCheatDestination {
    pub path: PathBuf,
    pub platform_directory: String,
    pub platform_directory_source: CheatPlatformDirectorySource,
    pub file_name: String,
    pub name_source: CheatDestinationNameSource,
    /// What is at the destination right now.
    pub state: DestinationState,
    /// True when installing replaces existing content.
    pub replaces_existing: bool,
}

/// A read-only description of moving an older EmuWiz platform-folder cheat
/// into RetroArch's core/content folder. This deliberately has no apply
/// method: an old install is never silently migrated by a normal install.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RetroArchCheatMigrationStatus {
    ReadyForExplicitReview,
    SourceMissing,
    SourceChangedSincePreview,
    DestinationConflict,
    DestinationAlreadyMatches,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct RetroArchCheatMigrationPreview {
    pub old_path: PathBuf,
    pub new_path: PathBuf,
    pub source_sha256: Option<String>,
    pub destination_sha256: Option<String>,
    pub status: RetroArchCheatMigrationStatus,
    pub detail: String,
}

/// Previews an explicit migration from the old platform-folder layout to the
/// verified RetroArch core/content layout. It reads and hashes files only.
pub fn preview_retroarch_cheat_migration(
    cheat_root: &Path,
    old_platform: &str,
    core: &str,
    content_basename: &str,
    expected_source_sha256: Option<&str>,
) -> Result<RetroArchCheatMigrationPreview, CheatInstallPlanError> {
    let old_platform = safe_file_stem(old_platform).ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
            None,
            "legacy RetroArch platform directory is unsafe",
        )
    })?;
    let core = safe_file_stem(core).ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
            None,
            "RetroArch core identifier is not a safe single directory name",
        )
    })?;
    let content = safe_file_stem(content_basename).ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationNameUnresolved,
            None,
            "RetroArch content identifier is not a safe filename",
        )
    })?;
    let old = assess_destination(
        cheat_root,
        std::ffi::OsStr::new(&old_platform),
        std::ffi::OsStr::new(&format!("{content}.cht")),
    )
    .map_err(|failure| destination_error(&failure))?;
    let new = assess_destination(
        cheat_root,
        std::ffi::OsStr::new(&core),
        std::ffi::OsStr::new(&format!("{content}.cht")),
    )
    .map_err(|failure| destination_error(&failure))?;
    let old_path = old.proposed_destination.path().to_path_buf();
    let new_path = new.proposed_destination.path().to_path_buf();
    let source_bytes = match fs::read(&old_path) {
        Ok(bytes) => bytes,
        Err(_) => {
            return Ok(RetroArchCheatMigrationPreview {
                old_path,
                new_path,
                source_sha256: None,
                destination_sha256: None,
                status: RetroArchCheatMigrationStatus::SourceMissing,
                detail: "no regular legacy platform-folder cheat file was found".to_string(),
            });
        }
    };
    let source_sha256 = hex_sha256(&source_bytes);
    if expected_source_sha256.is_some_and(|expected| expected != source_sha256) {
        return Ok(RetroArchCheatMigrationPreview {
            old_path,
            new_path,
            source_sha256: Some(source_sha256),
            destination_sha256: None,
            status: RetroArchCheatMigrationStatus::SourceChangedSincePreview,
            detail: "the legacy cheat file no longer matches the reviewed bytes".to_string(),
        });
    }
    let destination_sha256 = fs::read(&new_path).ok().map(|bytes| hex_sha256(&bytes));
    let (status, detail) = match destination_sha256.as_deref() {
        Some(hash) if hash == source_sha256 => (
            RetroArchCheatMigrationStatus::DestinationAlreadyMatches,
            "the core/content destination already contains the same bytes".to_string(),
        ),
        Some(_) => (
            RetroArchCheatMigrationStatus::DestinationConflict,
            "the core/content destination contains different bytes".to_string(),
        ),
        None => (
            RetroArchCheatMigrationStatus::ReadyForExplicitReview,
            "the legacy file can be reviewed for an explicit migration".to_string(),
        ),
    };
    Ok(RetroArchCheatMigrationPreview {
        old_path,
        new_path,
        source_sha256: Some(source_sha256),
        destination_sha256,
        status,
        detail,
    })
}

/// Resolves `<profile cheat root>/<core>/<name>.cht` for a bound RetroArch
/// core, or the legacy platform layout for callers that are not core-bound.
///
/// This is the libretro layout RetroArch's own cheat-file browser opens
/// into, so an installed file is reachable through Quick Menu -> Cheats ->
/// Load Cheat File without the user navigating elsewhere.
///
/// The platform directory is only ever this project's own canonical name;
/// an unrecognized platform is an error, never a sanitized passthrough of
/// untrusted text. The filename comes from the strongest available
/// identity, and which one was used is always reported so the user can see
/// it before confirming.
///
/// Path traversal, symlinked parents, symlinked destinations, and anything
/// resolving outside the profile's cheat directory are rejected by
/// [`assess_destination`] - the same checks every other adapter's
/// destinations go through.
pub fn resolve_cheat_destination(
    request: &CheatDestinationRequest,
) -> Result<ResolvedCheatDestination, CheatInstallPlanError> {
    if request.profile_cheat_root.as_os_str().is_empty()
        || !request.profile_cheat_root.is_absolute()
    {
        return Err(error(
            CheatInstallPlanErrorKind::DestinationRootUnavailable,
            Some(&request.profile_cheat_root),
            "the selected RetroArch profile declares no absolute cheat directory",
        ));
    }

    if request.retroarch_core_required && request.retroarch_core.is_none() {
        return Err(error(
            CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
            None,
            "RetroArch automatic placement requires an exact selected core",
        ));
    }

    if let Some(core) = &request.retroarch_core {
        let core = safe_file_stem(core).ok_or_else(|| {
            error(
                CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
                None,
                "RetroArch core identifier is not a safe single directory name",
            )
        })?;
        let (stem, name_source) = strongest_name(request).ok_or_else(|| {
            error(
                CheatInstallPlanErrorKind::DestinationNameUnresolved,
                None,
                "no safe filename could be derived from the content, playlist, or catalogue name",
            )
        })?;
        let file_name = format!("{stem}.cht");
        let assessment = assess_destination(
            &request.profile_cheat_root,
            std::ffi::OsStr::new(&core),
            std::ffi::OsStr::new(&file_name),
        )
        .map_err(|failure| destination_error(&failure))?;
        return Ok(ResolvedCheatDestination {
            path: assessment.proposed_destination.path().to_path_buf(),
            platform_directory: core.to_string(),
            platform_directory_source: CheatPlatformDirectorySource::CanonicalPlatformName,
            file_name,
            name_source,
            replaces_existing: assessment.destination_state == DestinationState::RegularFile,
            state: assessment.destination_state,
        });
    }

    let platform_hint = request.platform.as_deref().ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
            None,
            "the archive has no platform, so no cheat directory can be chosen",
        )
    })?;
    let canonical = canonical_platform_for_alias(platform_hint).ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationPlatformUnresolved,
            None,
            format!("platform {platform_hint:?} is not one this build recognizes"),
        )
    })?;
    // Prefer a directory the profile already has. A real RetroArch cheat
    // root is laid out by libretro database name, and installing into a
    // second, differently-named directory for the same system would leave
    // the file somewhere the user does not expect to look, next to - rather
    // than among - the cheat files already there.
    let (platform_directory, platform_directory_source) =
        match existing_platform_directory(&request.profile_cheat_root, canonical) {
            Some(existing) => (
                existing,
                CheatPlatformDirectorySource::ExistingProfileDirectory,
            ),
            None => (
                canonical.to_string(),
                CheatPlatformDirectorySource::CanonicalPlatformName,
            ),
        };

    let (stem, name_source) = strongest_name(request).ok_or_else(|| {
        error(
            CheatInstallPlanErrorKind::DestinationNameUnresolved,
            None,
            "no safe filename could be derived from the content, playlist, or catalogue name",
        )
    })?;
    let file_name = format!("{stem}.cht");

    let assessment = assess_destination(
        &request.profile_cheat_root,
        std::ffi::OsStr::new(&platform_directory),
        std::ffi::OsStr::new(&file_name),
    )
    .map_err(|failure| destination_error(&failure))?;

    Ok(ResolvedCheatDestination {
        path: assessment.proposed_destination.path().to_path_buf(),
        platform_directory,
        platform_directory_source,
        file_name,
        name_source,
        replaces_existing: assessment.destination_state == DestinationState::RegularFile,
        state: assessment.destination_state,
    })
}

/// Finds an existing subdirectory of the profile's cheat root whose name
/// resolves to `canonical`.
///
/// Only real directories are considered, and only their own names are
/// trusted - a name that does not resolve to a canonical platform is
/// ignored, never sanitized into one. Symlinked entries are skipped rather
/// than followed. Ties are broken by name so the choice is deterministic.
fn existing_platform_directory(cheat_root: &Path, canonical: &str) -> Option<String> {
    let mut matches: Vec<String> = Vec::new();
    for entry in fs::read_dir(cheat_root).ok()?.flatten() {
        if matches.len() >= MAX_PLATFORM_DIRECTORY_CANDIDATES {
            break;
        }
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_symlink() || !file_type.is_dir() {
            continue;
        }
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        if canonical_platform_for_alias(&name) == Some(canonical) && safe_file_stem(&name).is_some()
        {
            matches.push(name);
        }
    }
    matches.sort();
    matches.into_iter().next()
}

fn destination_error(failure: &DestinationSafetyError) -> CheatInstallPlanError {
    CheatInstallPlanError {
        kind: CheatInstallPlanErrorKind::DestinationUnsafe,
        path: Some(failure.path.clone()),
        detail: format!(
            "destination rejected ({:?}) at {}",
            failure.reason,
            failure.path.display()
        ),
    }
}

/// Picks the filename stem in strength order, skipping any candidate that
/// is not a safe single path component.
fn strongest_name(
    request: &CheatDestinationRequest,
) -> Option<(String, CheatDestinationNameSource)> {
    let ordered = [
        (
            request.content_basename.as_deref(),
            CheatDestinationNameSource::ContentBasename,
        ),
        (
            request.playlist_name.as_deref(),
            CheatDestinationNameSource::PlaylistName,
        ),
        (
            Some(request.catalogue_name.as_str()),
            CheatDestinationNameSource::CatalogueName,
        ),
    ];
    ordered.into_iter().find_map(|(value, source)| {
        let stem = safe_file_stem(value?)?;
        Some((stem, source))
    })
}

/// Accepts a value only if it is already a safe, single path component.
/// Deliberately does not strip separators or traversal tokens: laundering
/// an unsafe name into a safe-looking one is exactly how a destination ends
/// up somewhere nobody intended.
fn safe_file_stem(value: &str) -> Option<String> {
    let trimmed = value.trim().trim_end_matches('.').trim();
    if trimmed.is_empty()
        || trimmed == "."
        || trimmed == ".."
        || trimmed.starts_with('.')
        || trimmed.contains(['/', '\\', '\0'])
        || trimmed.chars().any(char::is_control)
        || trimmed.len() > 200
    {
        return None;
    }
    // A `.cht` already on the end would otherwise produce `Game.cht.cht`.
    let trimmed = trimmed
        .strip_suffix(".cht")
        .or_else(|| trimmed.strip_suffix(".CHT"))
        .unwrap_or(trimmed)
        .trim();
    (!trimmed.is_empty()).then(|| trimmed.to_string())
}

// ---------------------------------------------------------------------
// 4. Staging the generated file
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StagedCheatFile {
    /// The private root the staged file lives in - passed to
    /// [`super::shared_transaction::build_shared_transaction_plan`] as the
    /// approved source root.
    pub staging_root: PathBuf,
    pub path: PathBuf,
    pub digest: String,
    pub contents: String,
    pub selected_cheat_count: usize,
    pub enabled_cheat_count: usize,
}

/// Renders the selected cheats and writes them into a private staging
/// directory.
///
/// The staging directory is what the transaction machinery treats as the
/// approved source root; it exists because that machinery installs *files*
/// by digest, and a generated subset has no file in the catalogue to point
/// at. The catalogue itself is never written to.
///
/// The write is atomic: content goes to a temporary name in the same
/// directory and is renamed into place, so a staged path never exists in a
/// half-written state.
pub fn stage_generated_cheat_file(
    staging_root: &Path,
    file_name: &str,
    entries: &[ChtInstallEntry],
    extra_comments: &[String],
) -> Result<StagedCheatFile, CheatInstallPlanError> {
    if entries.is_empty() {
        return Err(error(
            CheatInstallPlanErrorKind::NoSelectedCheats,
            None,
            "refusing to stage a cheat file with no cheats in it",
        ));
    }
    let Some(safe_name) = safe_file_stem(file_name) else {
        return Err(error(
            CheatInstallPlanErrorKind::DestinationNameUnresolved,
            None,
            "staged filename is not a safe single path component",
        ));
    };

    let mut comments = vec![GENERATED_FILE_PROVENANCE.to_string()];
    comments.extend(extra_comments.iter().cloned());
    let contents = render_cht_file(entries, &comments);
    if contents.len() > MAX_GENERATED_FILE_BYTES {
        return Err(error(
            CheatInstallPlanErrorKind::GeneratedFileTooLarge,
            None,
            format!("generated cheat file exceeds {MAX_GENERATED_FILE_BYTES} bytes"),
        ));
    }

    fs::create_dir_all(staging_root).map_err(|failure| {
        error(
            CheatInstallPlanErrorKind::StagingUnavailable,
            Some(staging_root),
            format!("staging directory unavailable: {failure}"),
        )
    })?;

    let path = staging_root.join(format!("{safe_name}.cht"));
    let temporary = staging_root.join(format!(".{safe_name}.cht.partial"));
    let mut file = fs::File::create(&temporary).map_err(|failure| {
        error(
            CheatInstallPlanErrorKind::StagingUnavailable,
            Some(&temporary),
            format!("staged file could not be created: {failure}"),
        )
    })?;
    file.write_all(contents.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|failure| {
            error(
                CheatInstallPlanErrorKind::StagingUnavailable,
                Some(&temporary),
                format!("staged file could not be written: {failure}"),
            )
        })?;
    drop(file);
    fs::rename(&temporary, &path).map_err(|failure| {
        let _ = fs::remove_file(&temporary);
        error(
            CheatInstallPlanErrorKind::StagingUnavailable,
            Some(&path),
            format!("staged file could not be finalized: {failure}"),
        )
    })?;

    Ok(StagedCheatFile {
        staging_root: staging_root.to_path_buf(),
        path,
        digest: hex_sha256(contents.as_bytes()),
        contents,
        selected_cheat_count: entries.len(),
        enabled_cheat_count: entries.iter().filter(|entry| entry.enabled).count(),
    })
}

// ---------------------------------------------------------------------
// 5. Preview
// ---------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct CheatInstallPreviewRequest {
    pub selected_archive: PathBuf,
    pub platform: Option<String>,
    /// The verified identity string recorded in the journal and history.
    pub verified_identity: String,
    pub destination: ResolvedCheatDestination,
    pub profile_cheat_root: PathBuf,
    pub staged: StagedCheatFile,
    pub match_strength: PreviewMatchStrength,
}

#[derive(Debug, Clone)]
pub struct CheatInstallPreview {
    pub report: SharedPreviewReport,
    pub destination: ResolvedCheatDestination,
    pub staged: StagedCheatFile,
}

/// Wraps the staged file in the same shared preview every adapter uses, so
/// apply, backup, verification, journalling, and rollback are shared code
/// rather than a parallel implementation.
pub fn build_cheat_install_preview(
    request: &CheatInstallPreviewRequest,
) -> Result<CheatInstallPreview, CheatInstallPlanError> {
    let relative = request
        .destination
        .path
        .strip_prefix(&request.profile_cheat_root)
        .map_err(|_| {
            error(
                CheatInstallPlanErrorKind::DestinationUnsafe,
                Some(&request.destination.path),
                "resolved destination is not inside the profile cheat directory",
            )
        })?
        .to_path_buf();

    let report = build_shared_preview(&SharedPreviewRequest {
        adapter: PreviewAdapter::RetroArch,
        selected_archive: request.selected_archive.clone(),
        platform: request.platform.clone(),
        identity: PreviewIdentity {
            kind: PreviewIdentityKind::RetroArchCatalogueMatch,
            state: PreviewIdentityState::Verified,
            value: Some(request.verified_identity.clone()),
            archive_path: request.selected_archive.clone(),
            revision: None,
        },
        destination_root: request.profile_cheat_root.clone(),
        source_items: vec![PreviewSourceItem {
            adapter: PreviewAdapter::RetroArch,
            source_path: request.staged.path.clone(),
            expected_source_digest: Some(request.staged.digest.clone()),
            destination_relative_paths: vec![relative],
            match_strength: request.match_strength,
        }],
    })
    .map_err(|failure| preview_error(&failure))?;

    Ok(CheatInstallPreview {
        report,
        destination: request.destination.clone(),
        staged: request.staged.clone(),
    })
}

fn preview_error(failure: &SharedPreviewError) -> CheatInstallPlanError {
    CheatInstallPlanError {
        kind: CheatInstallPlanErrorKind::PreviewFailed,
        path: None,
        detail: failure.to_string(),
    }
}

/// Maps a candidate's classification onto the shared preview's own strength
/// vocabulary, and refuses one that must never be installed.
/// Maps a chosen candidate's classification onto the shared preview
/// pipeline's own match-strength vocabulary.
///
/// This is only ever called for a candidate the user has already picked by
/// clicking it explicitly (`CheatWorkflowAction::SelectCandidate`), never
/// for one still sitting unresolved in the candidate list. That distinction
/// matters for `Ambiguous` and `Weak`: `shared_preview`'s own blocking rule
/// (`PreviewMatchStrength::Ambiguous` is always refused - see
/// `shared_preview.rs`) exists to stop an *automatic* process from ever
/// silently picking between tied or weakly-evidenced matches. A human
/// explicitly choosing one of them is exactly the disambiguation that rule
/// is protecting against skipping, so from this point on the chosen
/// candidate is installable the same way a `Strong` one is - never
/// auto-selected (that is decided earlier, in `cheat_candidates`), but no
/// longer blocked by a safety rule aimed at automatic selection.
pub fn match_strength_for_candidate(
    candidate: &CheatCandidate,
) -> Result<PreviewMatchStrength, CheatInstallPlanError> {
    use super::cheat_candidates::CheatCandidateClassification as Classification;
    match candidate.classification {
        Classification::VerifiedExact => Ok(PreviewMatchStrength::VerifiedExact),
        Classification::Strong | Classification::Ambiguous | Classification::Weak => {
            Ok(PreviewMatchStrength::Strong)
        }
        Classification::CrossPlatform | Classification::Unsupported => Err(error(
            CheatInstallPlanErrorKind::CandidateNotInstallable,
            None,
            format!(
                "a {} candidate can never be installed",
                candidate.classification.label().to_lowercase()
            ),
        )),
    }
}

fn hex_sha256(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[cfg(test)]
mod tests;
