//! Pure, selected-only launch derivatives for cheats.
//!
//! This is the `patch_manager` half of the launch-composition seam:
//!
//! ```text
//! explicitly selected entries  ->  derivative bytes + provenance
//! ```
//!
//! It performs no filesystem access, spawns nothing, and never touches a
//! save path. The `launch` layer decides where the bytes live (a
//! launch-owned scratch tree) and how they are granted. Nothing here can
//! modify the source cheat file: it only receives already-parsed entries and
//! returns fresh bytes that carry a reference back to their source.

use std::collections::BTreeSet;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use super::cht_document::{ChtEntry, ChtInstallEntry, render_cht_file};

/// Upper bound on entries in one launch derivative. A launch composes what the
/// user explicitly picked, not a catalogue.
pub const MAX_LAUNCH_DERIVATIVE_ENTRIES: usize = 512;

/// Where a cheat came from. This is a reference, never authority: holding one
/// does not permit writing to `source_path`.
///
/// Integration seam: Batch 3's richer provenance record can be projected into
/// this shape (provider, stable source id, digest) without changing consumers.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct CheatSourceReference {
    pub provider: String,
    pub source_id: String,
    pub source_path: Option<PathBuf>,
    pub source_sha256: Option<String>,
    pub entry_index: Option<u32>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CheatLaunchDerivativeKind {
    RetroArchCht,
}

/// One explicitly selected implementation of one logical cheat.
#[derive(Clone, Copy, Debug)]
pub struct CheatDerivativeInput<'a> {
    pub logical_id: &'a str,
    pub variant_id: &'a str,
    pub source: &'a CheatSourceReference,
    pub entry: &'a ChtEntry,
}

/// What one derivative entry was built from.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheatDerivativeEntryRecord {
    pub logical_id: String,
    pub variant_id: String,
    pub source: CheatSourceReference,
    pub source_entry_index: u32,
    pub output_index: usize,
    pub title: String,
}

/// Generated bytes plus the evidence of what produced them.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheatLaunchDerivative {
    /// Relative to the launch-owned cheat directory; never absolute.
    pub relative_name: String,
    pub kind: CheatLaunchDerivativeKind,
    pub bytes: Vec<u8>,
    pub sha256: String,
    pub entries: Vec<CheatDerivativeEntryRecord>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CheatDerivativeError {
    NoEntries,
    TooManyEntries {
        count: usize,
    },
    /// Two variants of the same logical cheat were supplied. Conflicting
    /// implementations are never emitted together.
    DuplicateLogicalCheat {
        logical_id: String,
    },
    /// The entry has no code or a blocking warning; it can never be rendered.
    EntryNotSelectable {
        logical_id: String,
        variant_id: String,
    },
    UnsafeNamePart {
        part: String,
    },
}

fn safe_name_part(part: &str) -> bool {
    !part.is_empty()
        && part.len() <= 200
        && part != "."
        && part != ".."
        && !part.contains(['/', '\\', '\0'])
        && !part.chars().any(char::is_control)
}

/// Renders a RetroArch `.cht` containing only the supplied entries, all
/// enabled, in a deterministic order (by logical id, then variant id) with
/// contiguous indexes from zero. Input order never affects the output.
pub fn render_retroarch_selected_derivative(
    core_library_name: &str,
    content_basename: &str,
    inputs: &[CheatDerivativeInput<'_>],
) -> Result<CheatLaunchDerivative, CheatDerivativeError> {
    for part in [core_library_name, content_basename] {
        if !safe_name_part(part) {
            return Err(CheatDerivativeError::UnsafeNamePart {
                part: part.to_string(),
            });
        }
    }
    if inputs.is_empty() {
        return Err(CheatDerivativeError::NoEntries);
    }
    if inputs.len() > MAX_LAUNCH_DERIVATIVE_ENTRIES {
        return Err(CheatDerivativeError::TooManyEntries {
            count: inputs.len(),
        });
    }
    let mut seen = BTreeSet::new();
    for input in inputs {
        if !seen.insert(input.logical_id) {
            return Err(CheatDerivativeError::DuplicateLogicalCheat {
                logical_id: input.logical_id.to_string(),
            });
        }
    }

    let mut ordered: Vec<&CheatDerivativeInput<'_>> = inputs.iter().collect();
    ordered.sort_by(|left, right| {
        (left.logical_id, left.variant_id).cmp(&(right.logical_id, right.variant_id))
    });

    let mut install = Vec::with_capacity(ordered.len());
    let mut records = Vec::with_capacity(ordered.len());
    for (position, input) in ordered.iter().enumerate() {
        let Some(entry) = ChtInstallEntry::from_entry(input.entry, true) else {
            return Err(CheatDerivativeError::EntryNotSelectable {
                logical_id: input.logical_id.to_string(),
                variant_id: input.variant_id.to_string(),
            });
        };
        records.push(CheatDerivativeEntryRecord {
            logical_id: input.logical_id.to_string(),
            variant_id: input.variant_id.to_string(),
            source: input.source.clone(),
            source_entry_index: input.entry.index,
            output_index: position,
            title: entry.description.clone(),
        });
        install.push(entry);
    }

    let sources: BTreeSet<String> = ordered
        .iter()
        .map(|input| format!("{}:{}", input.source.provider, input.source.source_id))
        .collect();
    let mut header =
        vec!["Generated by EmuWiz for one launch. Not a source cheat file.".to_string()];
    header.extend(
        sources
            .into_iter()
            .map(|source| format!("Source: {source}")),
    );

    let bytes = render_cht_file(&install, &header).into_bytes();
    let mut digest = Sha256::new();
    digest.update(&bytes);
    let sha256 = digest
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    Ok(CheatLaunchDerivative {
        relative_name: format!("{core_library_name}/{content_basename}.cht"),
        kind: CheatLaunchDerivativeKind::RetroArchCht,
        bytes,
        sha256,
        entries: records,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::patch_manager::parse_cht_text;

    fn source(id: &str) -> CheatSourceReference {
        CheatSourceReference {
            provider: "local".into(),
            source_id: id.into(),
            source_path: Some(PathBuf::from(format!("/library/cheats/{id}.cht"))),
            source_sha256: Some("ab".repeat(32)),
            entry_index: None,
        }
    }

    fn entries() -> Vec<ChtEntry> {
        parse_cht_text(
            "cheats = 3\n\
             cheat0_desc = \"Infinite Lives\"\ncheat0_code = \"8000AA00\"\ncheat0_enable = false\n\
             cheat1_desc = \"Max Ammo\"\ncheat1_code = \"8000BB00\"\ncheat1_enable = true\n\
             cheat2_desc = \"No Code\"\ncheat2_enable = false\n",
        )
        .unwrap()
        .entries
    }

    #[test]
    fn renders_only_supplied_entries_enabled_and_contiguous() {
        let parsed = entries();
        let src = source("a");
        let derivative = render_retroarch_selected_derivative(
            "Core",
            "Game",
            &[CheatDerivativeInput {
                logical_id: "max-ammo",
                variant_id: "v1",
                source: &src,
                entry: &parsed[1],
            }],
        )
        .unwrap();
        let text = String::from_utf8(derivative.bytes.clone()).unwrap();
        assert!(text.contains("cheats = 1\n"));
        assert!(text.contains("cheat0_desc = \"Max Ammo\""));
        assert!(text.contains("cheat0_enable = true"));
        assert!(!text.contains("Infinite Lives"), "unselected entry leaked");
        assert_eq!(derivative.relative_name, "Core/Game.cht");
        assert_eq!(derivative.entries[0].source_entry_index, 1);
        assert_eq!(derivative.entries[0].source, src);
    }

    #[test]
    fn output_is_independent_of_input_order() {
        let parsed = entries();
        let (a, b) = (source("a"), source("b"));
        let one = CheatDerivativeInput {
            logical_id: "a-cheat",
            variant_id: "v",
            source: &a,
            entry: &parsed[0],
        };
        let two = CheatDerivativeInput {
            logical_id: "b-cheat",
            variant_id: "v",
            source: &b,
            entry: &parsed[1],
        };
        let forward = render_retroarch_selected_derivative("C", "G", &[one, two]).unwrap();
        let backward = render_retroarch_selected_derivative("C", "G", &[two, one]).unwrap();
        assert_eq!(forward, backward);
        assert_eq!(forward.entries[0].logical_id, "a-cheat");
        assert_eq!(forward.entries[1].output_index, 1);
    }

    #[test]
    fn refuses_conflicting_variants_unselectable_entries_and_unsafe_names() {
        let parsed = entries();
        let src = source("a");
        let input =
            |logical: &'static str, variant: &'static str, entry: usize| CheatDerivativeInput {
                logical_id: logical,
                variant_id: variant,
                source: &src,
                entry: &parsed[entry],
            };
        assert_eq!(
            render_retroarch_selected_derivative(
                "C",
                "G",
                &[input("x", "1", 0), input("x", "2", 1)]
            ),
            Err(CheatDerivativeError::DuplicateLogicalCheat {
                logical_id: "x".into()
            })
        );
        assert!(matches!(
            render_retroarch_selected_derivative("C", "G", &[input("x", "1", 2)]),
            Err(CheatDerivativeError::EntryNotSelectable { .. })
        ));
        assert_eq!(
            render_retroarch_selected_derivative("C", "G", &[]),
            Err(CheatDerivativeError::NoEntries)
        );
        for bad in ["../x", "a/b", "", "..", "a\\b"] {
            assert!(matches!(
                render_retroarch_selected_derivative(bad, "G", &[input("x", "1", 0)]),
                Err(CheatDerivativeError::UnsafeNamePart { .. })
            ));
        }
    }
}
