//! Tests for the DOSBox config evidence module.

use super::*;
use crate::content_evidence::{ContentEvidenceConfidence, ContentEvidenceKind};

fn parsed(text: &str) -> DosboxConfigFact {
    parse_dosbox_config(text.as_bytes()).expect("should parse")
}

// --- Positive (section 8) -------------------------------------------------

#[test]
fn dosbox_and_autoexec_sections_are_a_verified_dos_layout() {
    let fact = parsed(
        "# generated by dosbox\n\
         [dosbox]\n\
         memsize = 16\n\
         machine=svga_s3\n\
         [autoexec]\n\
         mount c .\n\
         c:\n\
         game.exe\n",
    );
    assert!(fact.has_dosbox_section);
    assert!(fact.has_autoexec);
    assert_eq!(fact.autoexec_command_lines, 3);
    assert!(fact.option_lines >= 2);
    assert!(fact.is_verified_dos_layout());

    let evidence = observe_dosbox_config_evidence(&fact);
    assert_eq!(evidence.len(), 1);
    assert_eq!(evidence[0].kind, ContentEvidenceKind::BootStructure);
    assert_eq!(evidence[0].value, DOSBOX_CONFIG_AUTOEXEC);
    assert_eq!(
        evidence[0].confidence,
        ContentEvidenceConfidence::Corroborated
    );
}

#[test]
fn autoexec_only_config_is_valid_dosbox_syntax_and_verifies() {
    let fact = parsed("[autoexec]\nmount c .\nc:\nstuff.exe\n");
    assert!(fact.has_autoexec);
    assert!(!fact.has_dosbox_section);
    assert_eq!(fact.autoexec_command_lines, 3);
    assert!(fact.is_verified_dos_layout());
}

#[test]
fn section_names_are_matched_case_insensitively() {
    let fact = parsed("[DosBox]\ncore=auto\n[AUTOEXEC]\nECHO hi\n");
    assert!(fact.has_dosbox_section);
    assert!(fact.has_autoexec);
    assert!(fact.sections.contains(&"dosbox".to_string()));
    assert!(fact.sections.contains(&"autoexec".to_string()));
}

#[test]
fn whitespace_and_comments_are_ignored() {
    let fact = parsed(
        "   \n\
         # a comment\n\
         ; another comment style\n\
           [dosbox]   \n\
         \tcycles = max   # inline comment kept as part of value, line still counts\n\
         \n\
         [ autoexec ]\t\n\
             mount c .\n",
    );
    assert!(fact.has_dosbox_section);
    assert!(fact.has_autoexec);
    assert_eq!(fact.autoexec_command_lines, 1);
    assert!(fact.is_verified_dos_layout());
}

#[test]
fn a_section_header_followed_by_a_comment_is_accepted() {
    let fact = parsed("[dosbox] # the main section\ncore=auto\n[autoexec] ; go\ngame\n");
    assert!(fact.has_dosbox_section && fact.has_autoexec);
    assert!(fact.is_verified_dos_layout());
}

#[test]
fn bounded_command_lines_are_counted_not_parsed() {
    let mut text = String::from("[autoexec]\n");
    for index in 0..50 {
        text.push_str(&format!("echo line {index}\n"));
    }
    let fact = parsed(&text);
    assert_eq!(fact.autoexec_command_lines, 50);
    // The commands themselves left no title/path/executable trace on the fact.
    let evidence = observe_dosbox_config_evidence(&fact);
    assert!(evidence.iter().all(|item| {
        !item.value.contains("echo") && item.kind != ContentEvidenceKind::ProductCode
    }));
}

#[test]
fn autoexec_command_line_count_is_bounded() {
    let mut text = String::from("[autoexec]\n");
    for _ in 0..(MAX_TRACKED_AUTOEXEC_LINES + 200) {
        text.push_str("rem x\n");
    }
    let fact = parsed(&text);
    assert_eq!(fact.autoexec_command_lines, MAX_TRACKED_AUTOEXEC_LINES);
}

#[test]
fn inspect_reads_a_config_file_from_disk() {
    let dir = std::env::temp_dir().join(format!(
        "archivefs-dosbox-conf-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|value| value.as_nanos())
            .unwrap_or(0)
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("dosbox.conf");
    std::fs::write(
        &path,
        b"[dosbox]\ncore=auto\n[autoexec]\nmount c .\ngame.exe\n",
    )
    .unwrap();
    let inspection = inspect_dosbox_config(&path, &crate::safe_read::TrustedRoots::none(), None);
    assert!(inspection.refusal.is_none());
    assert!(inspection.is_verified_dos_layout());
    let _ = std::fs::remove_dir_all(&dir);
}

// --- Negative (section 9) -----------------------------------------------

#[test]
fn empty_file_is_refused() {
    assert_eq!(parse_dosbox_config(b""), Err(DosboxConfigRefusal::Empty));
}

#[test]
fn random_text_with_no_section_yields_no_evidence() {
    let err = parse_dosbox_config(b"just some notes about this game\nnothing structured here\n")
        .unwrap_err();
    assert_eq!(err, DosboxConfigRefusal::NoSection);
}

#[test]
fn binary_nul_content_is_refused() {
    let mut bytes = b"[autoexec]\nmount c .\n".to_vec();
    bytes.push(0);
    bytes.extend_from_slice(&[0xff; 40]);
    assert_eq!(
        parse_dosbox_config(&bytes),
        Err(DosboxConfigRefusal::BinaryContent)
    );
}

#[test]
fn control_character_heavy_content_is_refused_even_without_nul() {
    let bytes: Vec<u8> = (0..400).map(|_| 0x01_u8).collect();
    assert_eq!(
        parse_dosbox_config(&bytes),
        Err(DosboxConfigRefusal::BinaryContent)
    );
}

#[test]
fn invalid_utf8_is_refused() {
    let bytes = [b'[', b'a', 0xC3, 0x28, b']', b'\n'];
    assert_eq!(
        parse_dosbox_config(&bytes),
        Err(DosboxConfigRefusal::InvalidUtf8)
    );
}

#[test]
fn a_section_header_with_no_closing_bracket_is_malformed() {
    let err = parse_dosbox_config(b"[dosbox]\ncore=auto\n[autoexec\nmount c .\n").unwrap_err();
    assert!(matches!(err, DosboxConfigRefusal::MalformedSection { .. }));
}

#[test]
fn a_fake_autoexec_line_without_brackets_is_not_a_section() {
    // "autoexec" as bare text (no brackets) is just a content line - it must
    // not be treated as the [autoexec] section.
    let err = parse_dosbox_config(b"autoexec\nmount c .\n").unwrap_err();
    assert_eq!(err, DosboxConfigRefusal::NoSection);
}

#[test]
fn section_name_inside_a_comment_does_not_count() {
    let err = parse_dosbox_config(b"# [autoexec]\n# [dosbox]\n; [autoexec] again\n").unwrap_err();
    assert_eq!(err, DosboxConfigRefusal::NoSection);
}

#[test]
fn trailing_junk_after_the_closing_bracket_is_malformed() {
    let err = parse_dosbox_config(b"[autoexec] and then some\nmount c .\n").unwrap_err();
    assert!(matches!(err, DosboxConfigRefusal::MalformedSection { .. }));
}

#[test]
fn empty_brackets_are_malformed() {
    let err = parse_dosbox_config(b"[]\nmount c .\n").unwrap_err();
    assert!(matches!(err, DosboxConfigRefusal::MalformedSection { .. }));
}

#[test]
fn dosbox_section_without_autoexec_is_not_dos_evidence() {
    let fact = parsed("[dosbox]\nmemsize=32\ncore=auto\n[cpu]\ncycles=max\n");
    assert!(fact.has_dosbox_section);
    assert!(!fact.has_autoexec);
    assert!(!fact.is_verified_dos_layout());
    assert!(observe_dosbox_config_evidence(&fact).is_empty());
}

#[test]
fn a_lone_autoexec_header_with_nothing_else_is_not_verified() {
    let fact = parsed("[autoexec]\n");
    assert!(fact.has_autoexec);
    assert_eq!(fact.autoexec_command_lines, 0);
    assert!(!fact.has_dosbox_section);
    assert!(!fact.is_verified_dos_layout());
    assert!(observe_dosbox_config_evidence(&fact).is_empty());
}

#[test]
fn an_over_long_line_is_refused() {
    let mut text = String::from("[autoexec]\n");
    text.push_str(&"a".repeat(MAX_DOSBOX_CONFIG_LINE_BYTES + 1));
    text.push('\n');
    assert!(matches!(
        parse_dosbox_config(text.as_bytes()),
        Err(DosboxConfigRefusal::LineTooLong { .. })
    ));
}

#[test]
fn an_over_large_file_is_refused() {
    let mut text = String::from("[autoexec]\n");
    while text.len() <= MAX_DOSBOX_CONFIG_BYTES {
        text.push_str("rem padding line\n");
    }
    assert!(matches!(
        parse_dosbox_config(text.as_bytes()),
        Err(DosboxConfigRefusal::TooLarge { .. })
    ));
}

#[test]
fn executable_names_in_autoexec_never_become_evidence_values() {
    let fact = parsed("[autoexec]\nmount c .\nc:\nSECRET_TITLE.EXE\ncall setup.bat\nboot -l c\n");
    assert!(fact.is_verified_dos_layout());
    for item in observe_dosbox_config_evidence(&fact) {
        assert_eq!(item.value, DOSBOX_CONFIG_AUTOEXEC);
        assert!(!item.value.to_lowercase().contains("secret_title"));
        assert!(!item.detail.to_lowercase().contains("secret_title"));
    }
}

#[test]
fn parsing_is_deterministic() {
    let text = "[dosbox]\ncore=auto\n[autoexec]\nmount c .\ngame.exe\n";
    assert_eq!(
        parse_dosbox_config(text.as_bytes()),
        parse_dosbox_config(text.as_bytes())
    );
}
